# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tsc:
      name: tsc
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: yarn install
      - name: tsc
        run: yarn compile
      - name: generate jsdoc
        run: yarn generate-docs
      - name: show docs
        run: ls docs
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "CI: Automated build push" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
